language: php

php:
  #- 5.5
  - 5.6
  #- 7.0
  #- hhvm

env:
  # - DRUPAL=8.1.x
  - DRUPAL=8.2.x
  - DRUPAL=8.3.x

matrix:
  allow_failures:
    - env: DRUPAL=8.3.x

sudo: false

git:
  depth: 3

before_script:
  - composer self-update
  - composer require --dev squizlabs/php_codesniffer:2.5.1
  - composer require drupal/coder:8.2.6
  - composer install
  - vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer

  # Require content_hub_drupal module.
  - composer require --prefer-source "drupal/content_hub_drupal @dev"

script:
  - vendor/bin/phpcs --standard=vendor/drupal/coder/coder_sniffer/Drupal --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt ./modules/content_hub_drupal/
  - vendor/bin/phpunit --configuration modules/content_hub_drupal/phpunit.xml --bootstrap core/tests/bootstrap.php --coverage-text=$TRAVIS_BUILD_DIR/coverage.txt


install:
  # - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN

  # Download Drupal and dependencies.
  - TESTDIR=$(pwd)
  - cd ..
  - git clone --depth 1 --branch ${DRUPAL} http://git.drupal.org/project/drupal.git drupal
  - cd drupal

  # Download Drupal core dependencies via lock file.
  - composer install

  # Add composer test dependencies to Drupal.
  - composer config repositories.drupal composer https://packages.drupal.org/8
  - composer config repositories.content_hub_drupal path $TESTDIR

after_script:
  # Print out coverage report.
  - head $TRAVIS_BUILD_DIR/coverage.txt