language: php

php:
  - 5.6
  - 7.0.15
  - 7.1.9

env:
  - DRUPAL=8.3.x
  - DRUPAL=8.4.x

cache:
  directories:
    - $HOME/.composer/cache

dist: trusty
sudo: required

services:
  - mysql

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:

  - sudo mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
  # first clone everything also into a subfolder, via a parent build folder
  - mkdir ../build
  - cp -R * ../build/
  - mv ../build/ ./

  # drop xdebug (need to read this for code coverage)
  - phpenv config-rm xdebug.ini

  # set memory limits (x_ makes it load last)
  - echo 'memory_limit="-1"' > x_memory.ini
  - phpenv config-add x_memory.ini
  - php -i | grep memory

  # alias some other values
  - alias php="php -d default_socket_timeout=1 -d xdebug.remote_enable=0 -d memory_limit=-1"

  - composer self-update

  # items for phpcs
  - composer require --dev drupal/coder ^8.2@stable
  - composer install
  - vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer

  # add composer's global bin directory to the path
  # see: https://github.com/drush-ops/drush#install---composer
  - export PATH="`composer global config bin-dir --absolute`:$PATH"
  # debug
  - composer global config bin-dir --absolute


install:
  - if [[ $DRUPAL == '8.3.x' ]]; then composer create-project acquia/lightning-project:8.2.* drupal --no-interaction --no-install; fi
  - if [[ $DRUPAL == '8.4.x' ]]; then composer create-project acquia/lightning-project:8.3.* drupal --no-interaction --no-install; fi
  - cd drupal

  # see https://github.com/drupal-composer/drupal-project/issues/175
  - composer config repositories.acquia_contenthub path ../build
  - composer config repositories.acquia_contenthub.symlink false
  - composer config --unset repositories.0
  - composer config repositories.drupal composer https://packages.drupal.org/8

  # Fix Drupal core version to 8.4.0 see https://github.com/acquia/lightning/issues/509
  - if [[ $DRUPAL == '8.4.x' ]];
    then composer require drupal/core:8.4.0 --no-update;
    else composer require drupal/core:$DRUPAL --no-update;
    fi
  - composer require drupal/acquia_contenthub:*
  - cat composer.json

  # Adding paragraphs contrib module.
  - composer require drupal/entity_reference_revisions:1.3 --profile
  - composer require drupal/paragraphs:1.2 --profile
  - composer require drupal/field_permissions --profile
  - composer require drupal/file_entity:2.0-beta4 --profile
  # Package of the lightning: 2.2.1 includes module the media_entity:2 - not intended for installation.
  - if [[ $DRUPAL == '8.4.x' ]]; then composer remove acquia/lightning; fi

  # Make changes (lightning:2.2.0) to install the media_entity: 1.6 which allows to pass all the tests.
  - if [[ $DRUPAL == '8.4.x' ]]; then composer require acquia/lightning:2.2.0; fi
  - composer update
  - composer install

  # Tweak PHP configuration.
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Adding drush downloaded by composer to the PATH.
  - export PATH="$PATH:`echo $PWD/vendor/drush/drush`"
  - echo $PATH

  - cd docroot
  - drush site-install lightning --db-url=mysql://root:@127.0.0.1/drupal --yes install_configure_form.enable_update_status_emails=NULL
  - cd ../..

before_script:
  # add always_populate_raw_post_data=-1 to php.ini
  - echo "always_populate_raw_post_data=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - vendor/bin/phpcs --standard=Drupal --warning-severity=2 --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt,md --ignore=ember/assets ./build
  - cd drupal/docroot
  - mkdir themes
  - cd core

  # Use phpunit assigned require in the composer in drupal. Otherwise drupal 8.3 does not pass all the tests for PHP 7.1.
  - if [[ ( $DRUPAL == '8.4.x' && ${TRAVIS_PHP_VERSION:0:3} != '5.6' ) || ( $DRUPAL == '8.3.x' ) ]]; then ../../vendor/phpunit/phpunit/phpunit --debug --group acquia_contenthub; fi
  - if [[ ( $DRUPAL == '8.4.x' && ${TRAVIS_PHP_VERSION:0:3} != '5.6' ) || ( $DRUPAL == '8.3.x' ) ]]; then ../../vendor/phpunit/phpunit/phpunit --debug --group acquia_contenthub_status; fi
  - cd ..

  # fix this first: The always_populate_raw_post_data PHP setting should be set to -1
  # - drush pm-enable acquia_contenthub_subscriber -y
  - drush pm-enable simpletest -y
  - nohup drush runserver localhost:8080 > /dev/null 2>&1 &
  - php core/scripts/run-tests.sh --php /home/travis/.phpenv/shims/php --verbose --url http://localhost:8080 --module acquia_contenthub
  - php core/scripts/run-tests.sh --php /home/travis/.phpenv/shims/php --verbose --url http://localhost:8080 --module acquia_contenthub_subscriber
