language: php

php:
  #- 5.5
  - 5.6
  #- 7.0
  #- hhvm

env:
  # - DRUPAL=8.1.x
  - DRUPAL=8.2.x
  # - DRUPAL=8.3.x

matrix:
  allow_failures:
    - env: DRUPAL=8.3.x
  fast_finish: true

sudo: false

services:
  - mysql

mysql:
  database: drupal
  username: travis
  encoding: utf8

before_install:

  # first clone everything also into a subfolder, via a parent build folder
  mkdir ../build
  cp -R * ../build/
  mv ../build/ ./

  # - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  # - sudo apt-get update & /dev/null
  - composer self-update

  # items for phpcs
  - composer require --dev squizlabs/php_codesniffer:2.5.1
  - composer require drupal/coder:8.2.6
  - composer install
  - vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer

install:
  - composer create-project acquia/lightning-project:^8.1.0 drupal --no-interaction --no-install
  - cd drupal
  - composer config --global repo.packagist composer https://packagist.org
  # see https://github.com/drupal-composer/drupal-project/issues/175
  - composer config --global repositories.0 composer https://packages.drupal.org/8
  - composer require drupal/core:$DRUPAL --no-update
  - composer config repositories.acquia-content-hub-d8 path ../build
  - composer config repositories.acquia-content-hub-d8.symlink false
  - composer require acquia/content-hub-d8
  # - composer update
  - composer install
  - cd ..
before_script:


script:
  - vendor/bin/phpcs -v --standard=vendor/drupal/coder/coder_sniffer/Drupal --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt ./modules/content_hub_drupal/
  - cd drupal/docroot
  - mkdir themes
  - cd modules/contrib/
  - mkdir content-hub-d8_
  - cp -R content-hub-d8/* content-hub-d8_
  - mv content-hub-d8_ content-hub-d8
  # - sed -i.bak 's/core/..\/core/' phpunit.xml
  # - vendor/bin/phpunit --configuration phpunit.xml --bootstrap core/tests/bootstrap.php
  - phpunit --configuration phpunit.xml