# Schema for the configuration files of the Acquia Content Hub module.
acquia_contenthub.admin_settings:
  type: config_object
  label: 'Acquia Content Hub admin settings'
  mapping:
    hostname:
      type: string
      label: "Content Hub API Hostname."
    api_key:
      type: string
      label: "Content Hub API Key."
    secret_key:
      type: string
      label: "Content Hub API Secret Key."
    rewrite_domain:
      type: string
      label: "Rewrite current domain to the domain set in this variable to 'fool' content hub where to fetch the content from. Useful with tunnels such as ngrok."
    client_name:
      type: string
      label: "Name of the current site as known in Acquia Content Hub."
    origin:
      type: string
      label: "Content Hub Token for this site."

acquia_contenthub.entity_config:
  type: config_object
  label: 'Acquia Content Hub entity configuration settings'
  mapping:
    user_role:
      type: string
      label: "Role to use when converting an Entity to a CDF with or without Metadata"
    entities:
      type: sequence
      label: "Entity Configuration"
      sequence:
        type: sequence
        label: 'A specific entity type configuration'
        sequence:
          type: mapping
          label: 'A specific entity bundle configuration'
          mapping:
            enable_index:
              type: integer
              label: 'Defines if this is being sent to Content Hub.'
            enable_viewmodes:
              type: integer
              label: 'Defines if we want to index view modes to Content Hub.'
            rendering:
              type: sequence
              label: 'Defines which view modes are enabled for this entity bundle.'
              sequence:
                type: string
                label: 'An enabled view mode'
