<?php

/**
 * @file
 * Implements entity auto-updates through webhooks.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_acquia_contenthub_process_webhook_alter().
 */
function acquia_contenthub_subscriber_acquia_contenthub_process_webhook_alter($webhook) {
  $contenthub_imported_entities = \Drupal::service('acquia_contenthub.acquia_contenthub_imported_entities');
  $contenthub_import_controller = \Drupal::service('acquia_contenthub.acquia_contenthub_cdf.import_entity');
  $assets = $webhook['assets'];
  // Process every asset that comes in the webhook, other than the
  // post dependencies.
  foreach ($assets as $asset) {
    // @TODO: We need to exclude post-dependencies (entity dependent).
    // @TODO: We need to invoke the default rule.
    // rules_invoke_event('content_hub_event_webhook_landing', $asset);
    // For now, we are just importing anything that comes in.
    if ($contenthub_imported_entities->loadByUuid($asset['uuid']) !== FALSE) {
      $contenthub_import_controller->saveDrupalEntity($asset['uuid']);
    }
  }
}

/**
 * Implements hook_entity_delete().
 */
function acquia_contenthub_subscriber_entity_delete(EntityInterface $entity) {
  // @TODO: Discuss flags like $entity->importedFromContentHub. Refer CHMS-929.
  // @TODO: Make phpstrom 'goto function' work with Drupal-8 services.

  // Get entity's uuid. D8 has direct core function for it.
  // Note: Some config and non rename-able entities will return NULL.
  $entity_uuid = $entity->uuid();
  if (isset($entity_uuid)) {
    // If this is an imported entity, delete its track record.
    $contenthub_imported_entities = \Drupal::service('acquia_contenthub.acquia_contenthub_imported_entities');
    if ($imported_entity = $contenthub_imported_entities->loadByUuid($entity_uuid)) {
      $imported_entity->delete();
    }
  }
}
