<?php
/**
 * @file
 * Contains content_hub_connector.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function content_hub_connector_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.content_hub_connector':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Some info about Acquia Content Hub') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_entity_insert().
 */
function content_hub_connector_entity_insert(EntityInterface $entity) {
  /** @var \Drupal\content_hub_connector\EntityManager $entity_manager */
  $entity_manager = \Drupal::service('content_hub_connector.entity_manager');
  $entity_manager->entityAction($entity, 'INSERT');
}

/**
 * Implements hook_entity_update().
 */
function content_hub_connector_entity_update(EntityInterface $entity) {
  /** @var \Drupal\content_hub_connector\EntityManager $entity_manager */
  $entity_manager = \Drupal::service('content_hub_connector.entity_manager');
  $entity_manager->entityAction($entity, 'UPDATE');
}

/**
 * Implements hook_entity_delete().
 */
function content_hub_connector_entity_delete(EntityInterface $entity) {
  /** @var \Drupal\content_hub_connector\EntityManager $entity_manager */
  $entity_manager = \Drupal::service('content_hub_connector.entity_manager');
  $entity_manager->entityAction($entity, 'DELETE');
}
